# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Acme-Void
version:      0.02
version_from: Void.pm
installdirs:  site
requires:
    Class::BlackHole:              0.01
    Want:                          0.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
